config_metadata:
  author: "Mohamed Dhaoui"
  description: "Config file for clinical_trials"
  contact: "admin@admin.com"

datasource:
  name: clinical_trials
  description: clinical_trials data
  labels:
    confidency: C1
    business_entity: SELLOUT
    env: DEV
  pipeline:
    data_collection:
      file_path: 'data/'
      filename: '^(clinical_trials)(\.csv)$'
      file_type: csv
      file_options:
        separator: ","
        skip_lines: 0
    data_quality:
      min_num_row: 2
      required_columns: ["id","scientific_title","date","journal"]
    data_preprocessing:
      column_transformation:
          column_types:
            id: str
            scientific_title: str
            date: date
            journal: str
          remove_special_char:
            columns: [journal]
          remove_nans:
            columns: [scientific_title]
          column_rename:
            scientific_title: title