config_metadata:
  author: "Mohamed Dhaoui"
  description: "Config file for drugs"
  contact: "admin@admin.com"

datasource:
  name: drugs
  description: drugs data
  labels:
    confidency: C1
    business_entity: Retail
    env: DEV
  pipeline:
    data_collection:
      file_path: 'data/'
      filename: '^(drugs)(\.csv)$'
      file_type: csv
      file_options:
        separator: ","
        skip_lines: 0
    data_quality:
      min_num_row: 2
      required_columns: ["atccode","drug"]
    data_preprocessing:
      column_transformation:
          column_types:
            atccode: str
            drug: str
          remove_nans:
            columns: [drug]